stages:
  - build
  - test

minimum:
  stage: build
  tags:
    - clang7
  script:
    - curl -OLs https://www.soe.ucsc.edu/~elm/cse130/fall19/testing/check_submission && python3 check_submission https://www.soe.ucsc.edu/~elm/cse130/fall19/testing/check_submissions.conf
  artifacts:
    expire_in: 1 week

functional_test:
  stage: test
  tags:
    - clang7
  script:
    - curl -OLs https://www.soe.ucsc.edu/~elm/cse130/fall19/testing/check_submission && python3 check_submission https://www.soe.ucsc.edu/~elm/cse130/fall19/testing/check_submissions.conf test
  when:  manual

