stages:
  - build
  - test

minimum:
  stage: build
  tags:
    - clang7
  script:
    - curl -OLs https://teaching.ethanmiller.org/cse130/fall19-02/testing_infrastructure/check_submission && python3 check_submission https://teaching.ethanmiller.org/cse130/fall19-02/testing_infrastructure/check_submissions.conf
  artifacts:
    expire_in: 1 week

functional_test:
  stage: test
  tags:
    - clang7
  script:
    - curl -OLs https://teaching.ethanmiller.org/cse130/fall19-02/testing_infrastructure/check_submission && python3 check_submission https://teaching.ethanmiller.org/cse130/fall19-02/testing_infrastructure/check_submissions.conf test
  when:  manual

